In [3]:
import pandas as pd
import matplotlib.pyplot as plt
import IPython

In [4]:
data = pd.read_excel("ICU_prediction.xlsx")

In [5]:
data

,PATIENT_VISIT_IDENTIFIER,AGE_ABOVE65,AGE_PERCENTIL,GENDER,DISEASE GROUPING 1,DISEASE GROUPING 2,DISEASE GROUPING 3,DISEASE GROUPING 4,DISEASE GROUPING 5,DISEASE GROUPING 6,...,TEMPERATURE_DIFF,OXYGEN_SATURATION_DIFF,BLOODPRESSURE_DIASTOLIC_DIFF_REL,BLOODPRESSURE_SISTOLIC_DIFF_REL,HEART_RATE_DIFF_REL,RESPIRATORY_RATE_DIFF_REL,TEMPERATURE_DIFF_REL,OXYGEN_SATURATION_DIFF_REL,WINDOW,ICU
0,0,1,60th,0,0.0,0.0,0.0,0.0,1.0,1.0,...,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,0-2,0
1,0,1,60th,0,0.0,0.0,0.0,0.0,1.0,1.0,...,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,2-4,0
2,0,1,60th,0,0.0,0.0,0.0,0.0,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4-6,0
3,0,1,60th,0,0.0,0.0,0.0,0.0,1.0,1.0,...,-1.000000,-1.000000,NaN,NaN,NaN,NaN,-1.000000,-1.000000,6-12,0
4,0,1,60th,0,0.0,0.0,0.0,0.0,1.0,1.0,...,-0.238095,-0.818182,-0.389967,0.407558,-0.230462,0.096774,-0.242282,-0.814433,ABOVE_12,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1920,384,0,50th,1,0.0,0.0,0.0,0.0,0.0,0.0,...,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,0-2,0
1921,384,0,50th,1,0.0,0.0,0.0,0.0,0.0,0.0,...,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,2-4,0
1922,384,0,50th,1,0.0,0.0,0.0,0.0,0.0,0.0,...,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,4-6,0
1923,384,0,50th,1,0.0,0.0,0.0,0.0,0.0,0.0,...,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,6-12,0
1924,384,0,50th,1,0.0,0.0,1.0,0.0,0.0,0.0,...,-0.547619,-0.838384,-0.701863,-0.585967,-0.763868,-0.612903,-0.551337,-0.835052,ABOVE_12,0

In [6]:
data.shape

(1925, 231)

In [7]:
data.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1925 entries, 0 to 1924
Data columns (total 231 columns):
 #    Column                            Dtype
---   ------                            -----
 0    PATIENT_VISIT_IDENTIFIER          int64
 1    AGE_ABOVE65                       int64
 2    AGE_PERCENTIL                     object
 3    GENDER                            int64
 4    DISEASE GROUPING 1                float64
 5    DISEASE GROUPING 2                float64
 6    DISEASE GROUPING 3                float64
 7    DISEASE GROUPING 4                float64
 8    DISEASE GROUPING 5                float64
 9    DISEASE GROUPING 6                float64
 10   HTN                               float64
 11   IMMUNOCOMPROMISED                 float64
 12   OTHER                             float64
 13   ALBUMIN_MEDIAN                    float64
 14   ALBUMIN_MEAN                      float64
 15   ALBUMIN_MIN                       float64
 16   ALBUMIN_MAX                       float64
 17   ALBUMIN_DIFF                      float64
 18   BE_ARTERIAL_MEDIAN                float64
 19   BE_ARTERIAL_MEAN                  float64
 20   BE_ARTERIAL_MIN                   float64
 21   BE_ARTERIAL_MAX                   float64
 22   BE_ARTERIAL_DIFF                  float64
 23   BE_VENOUS_MEDIAN                  float64
 24   BE_VENOUS_MEAN                    float64
 25   BE_VENOUS_MIN                     float64
 26   BE_VENOUS_MAX                     float64
 27   BE_VENOUS_DIFF                    float64
 28   BIC_ARTERIAL_MEDIAN               float64
 29   BIC_ARTERIAL_MEAN                 float64
 30   BIC_ARTERIAL_MIN                  float64
 31   BIC_ARTERIAL_MAX                  float64
 32   BIC_ARTERIAL_DIFF                 float64
 33   BIC_VENOUS_MEDIAN                 float64
 34   BIC_VENOUS_MEAN                   float64
 35   BIC_VENOUS_MIN                    float64
 36   BIC_VENOUS_MAX                    float64
 37   BIC_VENOUS_DIFF                   float64
 38   BILLIRUBIN_MEDIAN                 float64
 39   BILLIRUBIN_MEAN                   float64
 40   BILLIRUBIN_MIN                    float64
 41   BILLIRUBIN_MAX                    float64
 42   BILLIRUBIN_DIFF                   float64
 43   BLAST_MEDIAN                      float64
 44   BLAST_MEAN                        float64
 45   BLAST_MIN                         float64
 46   BLAST_MAX                         float64
 47   BLAST_DIFF                        float64
 48   CALCIUM_MEDIAN                    float64
 49   CALCIUM_MEAN                      float64
 50   CALCIUM_MIN                       float64
 51   CALCIUM_MAX                       float64
 52   CALCIUM_DIFF                      float64
 53   CREATININ_MEDIAN                  float64
 54   CREATININ_MEAN                    float64
 55   CREATININ_MIN                     float64
 56   CREATININ_MAX                     float64
 57   CREATININ_DIFF                    float64
 58   FFA_MEDIAN                        float64
 59   FFA_MEAN                          float64
 60   FFA_MIN                           float64
 61   FFA_MAX                           float64
 62   FFA_DIFF                          float64
 63   GGT_MEDIAN                        float64
 64   GGT_MEAN                          float64
 65   GGT_MIN                           float64
 66   GGT_MAX                           float64
 67   GGT_DIFF                          float64
 68   GLUCOSE_MEDIAN                    float64
 69   GLUCOSE_MEAN                      float64
 70   GLUCOSE_MIN                       float64
 71   GLUCOSE_MAX                       float64
 72   GLUCOSE_DIFF                      float64
 73   HEMATOCRITE_MEDIAN                float64
 74   HEMATOCRITE_MEAN                  float64
 75   HEMATOCRITE_MIN                   float64
 76   HEMATOCRITE_MAX                   float64
 77   HEMATOCRITE_DIFF                  float64
 78   HEMOGLOBIN_MEDIAN                 float64
 79   HEMOGLOBIN_MEAN                   float64
 80   HEMOGLOBIN_MIN                    float64
 81   HEMOGLOBIN_MAX                    float64
 82   HEMOGLOBIN_DIFF                   float64
 83   INR_MEDIAN                        float64
 84   INR_MEAN                          float64
 85   INR_MIN                           float64
 86   INR_MAX                           float64
 87   INR_DIFF                          float64
 88   LACTATE_MEDIAN                    float64
 89   LACTATE_MEAN                      float64
 90   LACTATE_MIN                       float64
 91   LACTATE_MAX                       float64
 92   LACTATE_DIFF                      float64
 93   LEUKOCYTES_MEDIAN                 float64
 94   LEUKOCYTES_MEAN                   float64
 95   LEUKOCYTES_MIN                    float64
 96   LEUKOCYTES_MAX                    float64
 97   LEUKOCYTES_DIFF                   float64
 98   LINFOCITOS_MEDIAN                 float64
 99   LINFOCITOS_MEAN                   float64
 100  LINFOCITOS_MIN                    float64
 101  LINFOCITOS_MAX                    float64
 102  LINFOCITOS_DIFF                   float64
 103  NEUTROPHILES_MEDIAN               float64
 104  NEUTROPHILES_MEAN                 float64
 105  NEUTROPHILES_MIN                  float64
 106  NEUTROPHILES_MAX                  float64
 107  NEUTROPHILES_DIFF                 float64
 108  P02_ARTERIAL_MEDIAN               float64
 109  P02_ARTERIAL_MEAN                 float64
 110  P02_ARTERIAL_MIN                  float64
 111  P02_ARTERIAL_MAX                  float64
 112  P02_ARTERIAL_DIFF                 float64
 113  P02_VENOUS_MEDIAN                 float64
 114  P02_VENOUS_MEAN                   float64
 115  P02_VENOUS_MIN                    float64
 116  P02_VENOUS_MAX                    float64
 117  P02_VENOUS_DIFF                   float64
 118  PC02_ARTERIAL_MEDIAN              float64
 119  PC02_ARTERIAL_MEAN                float64
 120  PC02_ARTERIAL_MIN                 float64
 121  PC02_ARTERIAL_MAX                 float64
 122  PC02_ARTERIAL_DIFF                float64
 123  PC02_VENOUS_MEDIAN                float64
 124  PC02_VENOUS_MEAN                  float64
 125  PC02_VENOUS_MIN                   float64
 126  PC02_VENOUS_MAX                   float64
 127  PC02_VENOUS_DIFF                  float64
 128  PCR_MEDIAN                        float64
 129  PCR_MEAN                          float64
 130  PCR_MIN                           float64
 131  PCR_MAX                           float64
 132  PCR_DIFF                          float64
 133  PH_ARTERIAL_MEDIAN                float64
 134  PH_ARTERIAL_MEAN                  float64
 135  PH_ARTERIAL_MIN                   float64
 136  PH_ARTERIAL_MAX                   float64
 137  PH_ARTERIAL_DIFF                  float64
 138  PH_VENOUS_MEDIAN                  float64
 139  PH_VENOUS_MEAN                    float64
 140  PH_VENOUS_MIN                     float64
 141  PH_VENOUS_MAX                     float64
 142  PH_VENOUS_DIFF                    float64
 143  PLATELETS_MEDIAN                  float64
 144  PLATELETS_MEAN                    float64
 145  PLATELETS_MIN                     float64
 146  PLATELETS_MAX                     float64
 147  PLATELETS_DIFF                    float64
 148  POTASSIUM_MEDIAN                  float64
 149  POTASSIUM_MEAN                    float64
 150  POTASSIUM_MIN                     float64
 151  POTASSIUM_MAX                     float64
 152  POTASSIUM_DIFF                    float64
 153  SAT02_ARTERIAL_MEDIAN             float64
 154  SAT02_ARTERIAL_MEAN               float64
 155  SAT02_ARTERIAL_MIN                float64
 156  SAT02_ARTERIAL_MAX                float64
 157  SAT02_ARTERIAL_DIFF               float64
 158  SAT02_VENOUS_MEDIAN               float64
 159  SAT02_VENOUS_MEAN                 float64
 160  SAT02_VENOUS_MIN                  float64
 161  SAT02_VENOUS_MAX                  float64
 162  SAT02_VENOUS_DIFF                 float64
 163  SODIUM_MEDIAN                     float64
 164  SODIUM_MEAN                       float64
 165  SODIUM_MIN                        float64
 166  SODIUM_MAX                        float64
 167  SODIUM_DIFF                       float64
 168  TGO_MEDIAN                        float64
 169  TGO_MEAN                          float64
 170  TGO_MIN                           float64
 171  TGO_MAX                           float64
 172  TGO_DIFF                          float64
 173  TGP_MEDIAN                        float64
 174  TGP_MEAN                          float64
 175  TGP_MIN                           float64
 176  TGP_MAX                           float64
 177  TGP_DIFF                          float64
 178  TTPA_MEDIAN                       float64
 179  TTPA_MEAN                         float64
 180  TTPA_MIN                          float64
 181  TTPA_MAX                          float64
 182  TTPA_DIFF                         float64
 183  UREA_MEDIAN                       float64
 184  UREA_MEAN                         float64
 185  UREA_MIN                          float64
 186  UREA_MAX                          float64
 187  UREA_DIFF                         float64
 188  DIMER_MEDIAN                      float64
 189  DIMER_MEAN                        float64
 190  DIMER_MIN                         float64
 191  DIMER_MAX                         float64
 192  DIMER_DIFF                        float64
 193  BLOODPRESSURE_DIASTOLIC_MEAN      float64
 194  BLOODPRESSURE_SISTOLIC_MEAN       float64
 195  HEART_RATE_MEAN                   float64
 196  RESPIRATORY_RATE_MEAN             float64
 197  TEMPERATURE_MEAN                  float64
 198  OXYGEN_SATURATION_MEAN            float64
 199  BLOODPRESSURE_DIASTOLIC_MEDIAN    float64
 200  BLOODPRESSURE_SISTOLIC_MEDIAN     float64
 201  HEART_RATE_MEDIAN                 float64
 202  RESPIRATORY_RATE_MEDIAN           float64
 203  TEMPERATURE_MEDIAN                float64
 204  OXYGEN_SATURATION_MEDIAN          float64
 205  BLOODPRESSURE_DIASTOLIC_MIN       float64
 206  BLOODPRESSURE_SISTOLIC_MIN        float64
 207  HEART_RATE_MIN                    float64
 208  RESPIRATORY_RATE_MIN              float64
 209  TEMPERATURE_MIN                   float64
 210  OXYGEN_SATURATION_MIN             float64
 211  BLOODPRESSURE_DIASTOLIC_MAX       float64
 212  BLOODPRESSURE_SISTOLIC_MAX        float64
 213  HEART_RATE_MAX                    float64
 214  RESPIRATORY_RATE_MAX              float64
 215  TEMPERATURE_MAX                   float64
 216  OXYGEN_SATURATION_MAX             float64
 217  BLOODPRESSURE_DIASTOLIC_DIFF      float64
 218  BLOODPRESSURE_SISTOLIC_DIFF       float64
 219  HEART_RATE_DIFF                   float64
 220  RESPIRATORY_RATE_DIFF             float64
 221  TEMPERATURE_DIFF                  float64
 222  OXYGEN_SATURATION_DIFF            float64
 223  BLOODPRESSURE_DIASTOLIC_DIFF_REL  float64
 224  BLOODPRESSURE_SISTOLIC_DIFF_REL   float64
 225  HEART_RATE_DIFF_REL               float64
 226  RESPIRATORY_RATE_DIFF_REL         float64
 227  TEMPERATURE_DIFF_REL              float64
 228  OXYGEN_SATURATION_DIFF_REL        float64
 229  WINDOW                            object
 230  ICU                               int64
dtypes: float64(225), int64(4), object(2)
memory usage: 3.4+ MB

In [8]:
data.select_dtypes(object)

     AGE_PERCENTIL    WINDOW
0             60th       0-2
1             60th       2-4
2             60th       4-6
3             60th      6-12
4             60th  ABOVE_12
...            ...       ...
1920          50th       0-2
1921          50th       2-4
1922          50th       4-6
1923          50th      6-12
1924          50th  ABOVE_12

[1925 rows x 2 columns]

In [9]:
data['AGE_P'] = data['AGE_PERCENTIL'].str.extract('(\d+)').astype(int)
data['AGE_P']

0       60
1       60
2       60
3       60
4       60
        ..
1920    50
1921    50
1922    50
1923    50
1924    50
Name: AGE_P, Length: 1925, dtype: int32

In [10]:
data.drop(['AGE_PERCENTIL','WINDOW'],axis=1,inplace=True)

In [11]:
data.columns

Index(['PATIENT_VISIT_IDENTIFIER', 'AGE_ABOVE65', 'GENDER',
       'DISEASE GROUPING 1', 'DISEASE GROUPING 2', 'DISEASE GROUPING 3',
       'DISEASE GROUPING 4', 'DISEASE GROUPING 5', 'DISEASE GROUPING 6', 'HTN',
       ...
       'TEMPERATURE_DIFF', 'OXYGEN_SATURATION_DIFF',
       'BLOODPRESSURE_DIASTOLIC_DIFF_REL', 'BLOODPRESSURE_SISTOLIC_DIFF_REL',
       'HEART_RATE_DIFF_REL', 'RESPIRATORY_RATE_DIFF_REL',
       'TEMPERATURE_DIFF_REL', 'OXYGEN_SATURATION_DIFF_REL', 'ICU', 'AGE_P'],
      dtype='object', length=230)

In [12]:
data.dropna(axis=0,inplace=True)

In [13]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 545 entries, 4 to 1924
Columns: 230 entries, PATIENT_VISIT_IDENTIFIER to AGE_P
dtypes: float64(225), int32(1), int64(4)
memory usage: 981.4 KB

In [14]:
data['ICU'].value_counts()

0    281
1    264
Name: ICU, dtype: int64

In [15]:
X = data.drop('ICU',axis=1)
y = data['ICU']

In [16]:
from sklearn.model_selection import train_test_split

In [17]:
X_train, X_test, y_train, y_test = train_test_split(
...     X, y, test_size=0.3, random_state=0)

X_train.shape , X_test.shape

((381, 229), (164, 229))

In [18]:
def correlation(dataset, threshold):
    col_corr = set()  # Set of all the names of correlated columns
    corr_matrix = dataset.corr()
    for i in range(len(corr_matrix.columns)):
        for j in range(i):
            if (corr_matrix.iloc[i, j]) > threshold: # we are interested in absolute coeff value
                colname = corr_matrix.columns[i]  # getting the name of column
                col_corr.add(colname)
    return col_corr

In [19]:
corr_features = correlation(X_train, 0.9)
len(set(corr_features))

123

In [20]:
X_train = X_train.drop(corr_features,axis=1)
X_test = X_test.drop(corr_features,axis=1)

In [21]:
X_train.head()

,PATIENT_VISIT_IDENTIFIER,AGE_ABOVE65,GENDER,DISEASE GROUPING 1,DISEASE GROUPING 2,DISEASE GROUPING 3,DISEASE GROUPING 4,DISEASE GROUPING 5,DISEASE GROUPING 6,HTN,...,HEART_RATE_MAX,RESPIRATORY_RATE_MAX,TEMPERATURE_MAX,OXYGEN_SATURATION_MAX,BLOODPRESSURE_DIASTOLIC_DIFF,BLOODPRESSURE_SISTOLIC_DIFF,HEART_RATE_DIFF,TEMPERATURE_DIFF,OXYGEN_SATURATION_DIFF,AGE_P
1615,323,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.223881,-0.090909,0.478261,0.684211,-0.843478,-0.803681,-0.984733,-1.000000,-0.939394,40
1396,279,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.492537,-0.636364,-0.014493,0.894737,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,50
824,164,1,0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,...,0.179104,-0.151515,0.362319,0.894737,-0.373913,-0.447853,-0.053435,-0.238095,0.959596,70
970,194,1,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.567164,-0.575758,0.014493,0.736842,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,80
889,177,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.044776,-0.333333,-0.014493,1.000000,-0.460870,-0.509202,-0.236641,-0.428571,-0.878788,10

In [22]:
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LogisticRegressionCV
from sklearn.pipeline import make_pipeline
from sklearn.metrics import confusion_matrix
from sklearn.metrics import roc_auc_score

In [23]:
def res(y_true,y_pred):
  tn, fp, fn, tp = confusion_matrix(y_true, y_pred).ravel()
  accuracy=(tp+tn)/(tp+fp+fn+tn)
  specificity = tn/(tn+fp)
  sensitivity=tp/(tp+fn)
  print("Accuracy:",accuracy*100)
  print("Sensitivity:",sensitivity*100)
  print("Specificity:",specificity*100)
  print("ROC_AUC_Score:",roc_auc_score(y_true, y_pred)*100)

In [24]:
lgc=make_pipeline(LogisticRegressionCV(cv=5,random_state=1,max_iter=100000))
lgc.fit(X_train, y_train)
y_pred=lgc.predict(X_test)
res(y_test,y_pred)

Accuracy: 85.97560975609755
Sensitivity: 89.55223880597015
Specificity: 83.50515463917526
ROC_AUC_Score: 86.5286967225727

In [25]:
from sklearn import svm
from sklearn.pipeline import make_pipeline

In [26]:
SVM_object = make_pipeline(svm.SVC(kernel='linear'))
SVM_object.fit(X_train,y_train)
y_pred=SVM_object.predict(X_test)
res(y_test,y_pred)

Accuracy: 83.53658536585365
Sensitivity: 88.05970149253731
Specificity: 80.41237113402062
ROC_AUC_Score: 84.23603631327897